name: Unit Test
on:
  push:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit Test
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}