name: Unit Test
on:
  push:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          # add another server to the ~/.m2/settings.xml default config.
          # We use a "Bearer" token for authorization to get packages from other repositories.
          servers: '[
          {"id": "github-event-bus-repos","configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.PCKGS_PAT }}"}}}}]'
      - name: Unit Test
        run: mvn test
        # download of parent POM fails with repository
        #  <id>github</id>
        #  <url>https://maven.pkg.github.com/kexbin/event-bus-test-app</url>
        # and GITHUB_TOKEN
        # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}